version: '3.8'

services:
  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=4Uh9ApgvB1TWpAJL/DQ+KbeAjTTYlfs1l7+d3n4ZViPIi9U2sBwKfeOm
    volumes:
      - superset_data:/app/superset
    command: ["sh", "-c", "pip install psycopg2-binary pillow && superset fab create-admin --username admin --password admin --email admin@example.com --firstname Admin --lastname User && superset db upgrade && superset init && superset run -p 8088 --host 0.0.0.0 --with-threads"]

volumes:
  superset_data:

# Экспорт всех настроек superset: docker cp superset:/app/superset_home/superset.db ./ss_db.db
# Импорт всех настроек superset: docker cp ./ss_db.db superset:/app/superset_home/superset.db